Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -156,7 +156,7 @@ jobs:
           IMAGE_TAG: ${{ github.sha }}
         run: |
           echo "Scanning Docker image for vulnerabilities..."
-          trivy image --exit-code 1 --severity CRITICAL,HIGH ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/tictac:$IMAGE_TAG || (echo "Vulnerability scan failed!" && exit 1)
+          trivy image --exit-code 1 --severity HIGH ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.ap-south-1.amazonaws.com/tictac:$IMAGE_TAG || (echo "Vulnerability scan failed!" && exit 1)
 
       - name: Push Docker Image to ECR
         env:
